# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bea4cef038b6ec86aacae1e7be34655bc4bb8462f9dd19e27aa5771dc6cc04add2b272d5a7359f8ef590edde1a21ff62093f9e4ee1f4272ec76993577c1efba3

test:
  secret_key_base: 0dd434dabd95d734b2d42d04cc3612dc08756e02ee89169742b24a0bf370e78c8cf14e9781aa2139a465e16df7f7e572a0c27b6a44aeedf6713e108b06a5e164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 61151464f1dbec1e8bbe906eb0549e449bd199ea7668224a592461171be7ba9413a09782995410251940b099f9ec77cda16b165c9934c4ed22be8dbe6cf6d55c
